spring:
  application:
      name: ToDoApp
  jpa:
    hibernate:
      ddl-auto : none
    show-sql : true
  datasource:
   url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/todo
   username: root
   password :
   driver-class-name : com.mysql.cj.jdbc.Driver
jwt:
  key : ${JWT_KEY}
  access-token-expiration : 3600000
  refresh-token-expiration: 86400000
